CREATE PROFILE Admin_P AS 
    ACCOUNT = ('$M0+EDUC&S&D&H', '$H0+EDUC&S&D&H'),
    SPOOL=100E6, 
    TEMPORARY=100E6,
    PASSWORD=(MAXLOGONATTEMPTS=3, LOCKEDUSEREXPIRE=5, MINCHAR=6, MAXCHAR=15, SPECCHAR='I', DIGITS ='Y');

CREATE PROFILE Student_P AS 
    ACCOUNT = ('$M0+EDUC&S&D&H', '$L0+EDUC&S&D&H'),
    SPOOL=100E6,
    TEMPORARY=100E6,
    PASSWORD=(MAXLOGONATTEMPTS=3, LOCKEDUSEREXPIRE=5, MINCHAR=6, MAXCHAR=15, SPECCHAR='I', DIGITS ='Y');

CREATE PROFILE Trainer_P AS 
    ACCOUNT = ('$M0+EDUC&S&D&H', '$H0+EDUC&S&D&H'),
    SPOOL=100E6, 
    TEMPORARY=100E6,
    PASSWORD=(MAXLOGONATTEMPTS=3, LOCKEDUSEREXPIRE=5, MINCHAR=6, MAXCHAR=15, SPECCHAR='I', DIGITS ='Y');

CREATE USER Sysdba FROM DBC AS PERM=500E6, PASSWORD=********, PROFILE = Admin_P;

CREATE DATABASE Spool_Reserve FROM DBC AS PERM = 25E6;

GRANT ALL           ON Sysdba	TO Sysdba WITH GRANT OPTION;
GRANT ROLE			TO Sysdba WITH GRANT OPTION;
GRANT PROFILE			TO Sysdba WITH GRANT OPTION;

GRANT SELECT, EXECUTE ON DBC	TO PUBLIC;
GRANT SELECT ON SYS_CALENDAR	TO PUBLIC;